---
# See the documentation for more information:
# https://packit.dev/docs/configuration/
specfile_path: mrack.spec

# add or remove files that should be synced
files_to_sync:
  - mrack.spec
  - README.md
  - .packit.yaml
  - gating.yaml

# name in upstream package repository/registry (e.g. in PyPI)
upstream_package_name: mrack
# downstream (Fedora) RPM package name
downstream_package_name: mrack
# mrack uses tag v(ver_number) and we need to make sure packit know what to expect
# see: https://packit.dev/docs/configuration/#upstream_tag_template
upstream_tag_template: "v{version}"

actions:
  create-archive:
    - "python3 setup.py sdist --dist-dir ."
    - "sh -c 'echo mrack-$(python3 setup.py --version).tar.gz'"
  get-current-version:
    - "python3 setup.py --version"

jobs:
  - job: tests
    trigger: pull_request
    targets: [fedora-all, epel-8, epel-9]

  - job: copr_build
    trigger: commit
    targets: [fedora-all, epel-8, epel-9]

  - job: copr_build
    trigger: release
    owner: "@freeipa"
    project: neoave
    targets: [fedora-all, epel-8, epel-9]

  - job: propose_downstream
    trigger: release
    dist_git_branches: [fedora-all, epel-8, epel-9]

  - job: koji_build
    trigger: commit
    dist_git_branches: [fedora-all, epel-8, epel-9]

  - job: bodhi_update
    trigger: commit
    dist_git_branches: [fedora-branched, epel-8, epel-9] # rawhide updates are created automatically
